import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const listings = [
  {
    name: "Sahiwal Cow",
    breed: "Purebred Sahiwal",
    category: "Cows",
    age: "3 years",
    weight: "350 kg",
    gender: "Female",
    price: 65000,
    description: "Healthy Sahiwal cow with excellent milk yield. Well-fed and vaccinated.",
    milkYield: "15L/day",
    image: "https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?w=600&h=400&fit=crop",
    location: "Lahore, Punjab",
    city: "Lahore",
    province: "Punjab",
    verified: true,
    featured: true,
    sellerName: "Muhammad Ali",
    phone: "+92 300 1234567",
  },
  {
    name: "German Shepherd Puppy",
    breed: "Imported Bloodline",
    category: "Dogs",
    age: "3 months",
    weight: "8 kg",
    gender: "Male",
    price: 25000,
    description: "Beautiful German Shepherd puppy with imported bloodline. First vaccine done.",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop",
    location: "Islamabad, ICT",
    city: "Islamabad",
    province: "Islamabad Capital Territory",
    verified: true,
    featured: true,
    sellerName: "Fatima Khan",
    phone: "+92 321 7654321",
  },
  {
    name: "Beetal Goat",
    breed: "Premium Beetal",
    category: "Goats",
    age: "1.5 years",
    weight: "45 kg",
    gender: "Male",
    price: 18000,
    description: "Premium quality Beetal goat, perfect for breeding.",
    image: "https://images.unsplash.com/photo-1535338454770-8be927b5a00b?w=600&h=400&fit=crop",
    location: "Rawalpindi, Punjab",
    city: "Rawalpindi",
    province: "Punjab",
    verified: true,
    featured: false,
    sellerName: "Ahmad Hassan",
    phone: "+92 333 1112233",
  },
  {
    name: "Persian Cat",
    breed: "Show Quality",
    category: "Cats",
    age: "8 months",
    weight: "4 kg",
    gender: "Female",
    price: 35000,
    description: "Show quality Persian cat with beautiful coat. Fully vaccinated.",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=400&fit=crop",
    location: "Karachi, Sindh",
    city: "Karachi",
    province: "Sindh",
    verified: true,
    featured: true,
    sellerName: "Ayesha Bibi",
    phone: "+92 345 6789012",
  },
  {
    name: "Nili-Ravi Buffalo",
    breed: "High Yield",
    category: "Buffalo",
    age: "4 years",
    weight: "550 kg",
    gender: "Female",
    price: 85000,
    description: "High yielding Nili-Ravi buffalo. Excellent health condition.",
    milkYield: "18L/day",
    image: "https://images.unsplash.com/photo-1614578829303-c4b2d880b7b6?w=600&h=400&fit=crop",
    location: "Multan, Punjab",
    city: "Multan",
    province: "Punjab",
    verified: true,
    featured: false,
    sellerName: "Usman Sheikh",
    phone: "+92 300 9876543",
  },
  {
    name: "Teddy Parrot Pair",
    breed: "Lutino & Grey",
    category: "Birds",
    age: "1 year",
    weight: "0.3 kg",
    gender: "Pair",
    price: 4500,
    description: "Beautiful teddy parrot pair, hand-raised and friendly.",
    image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&h=400&fit=crop",
    location: "Peshawar, KPK",
    city: "Peshawar",
    province: "Khyber Pakhtunkhwa",
    verified: true,
    featured: true,
    sellerName: "Zainab Malik",
    phone: "+92 312 4567890",
  },
  {
    name: "Labrador Retriever",
    breed: "English Cream",
    category: "Dogs",
    age: "2 months",
    weight: "5 kg",
    gender: "Male",
    price: 30000,
    description: "Adorable English Cream Labrador puppy. KC registered parents.",
    image: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&h=400&fit=crop",
    location: "Faisalabad, Punjab",
    city: "Faisalabad",
    province: "Punjab",
    verified: true,
    featured: true,
    sellerName: "Bilal Ahmed",
    phone: "+92 345 1112233",
  },
  {
    name: "Cholistani Cow",
    breed: "Purebred Cholistani",
    category: "Cows",
    age: "5 years",
    weight: "400 kg",
    gender: "Female",
    price: 75000,
    description: "Purebred Cholistani cow with excellent milk production.",
    milkYield: "12L/day",
    image: "https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=600&h=400&fit=crop",
    location: "Bahawalpur, Punjab",
    city: "Bahawalpur",
    province: "Punjab",
    verified: true,
    featured: false,
    sellerName: "Saad Qureshi",
    phone: "+92 300 5556677",
  },
  {
    name: "Kamori Goat",
    breed: "Premium Kamori",
    category: "Goats",
    age: "2 years",
    weight: "35 kg",
    gender: "Female",
    price: 15000,
    description: "Premium Kamori goat from Sindh. Healthy and well-maintained.",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600&h=400&fit=crop",
    location: "Hyderabad, Sindh",
    city: "Hyderabad",
    province: "Sindh",
    verified: true,
    featured: false,
    sellerName: "Imran Shah",
    phone: "+92 333 9998877",
  },
  {
    name: "Budgerigar Pair",
    breed: "Rainbow Series",
    category: "Birds",
    age: "6 months",
    weight: "0.06 kg",
    gender: "Pair",
    price: 2500,
    description: "Colorful budgerigar pair. Very active and cheerful.",
    image: "https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=600&h=400&fit=crop",
    location: "Quetta, Balochistan",
    city: "Quetta",
    province: "Balochistan",
    verified: false,
    featured: false,
    sellerName: "Nadia Parveen",
    phone: "+92 312 7778899",
  },
  {
    name: "Rabbit - Holland Lop",
    breed: "Show Quality",
    category: "Rabbits",
    age: "4 months",
    weight: "1.5 kg",
    gender: "Female",
    price: 8000,
    description: "Show quality Holland Lop rabbit with perfect markings.",
    image: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=400&fit=crop",
    location: "Sialkot, Punjab",
    city: "Sialkot",
    province: "Punjab",
    verified: true,
    featured: false,
    sellerName: "Hira Khan",
    phone: "+92 345 3334455",
  },
  {
    name: "Siamese Cat",
    breed: "Traditional Seal Point",
    category: "Cats",
    age: "1 year",
    weight: "3.5 kg",
    gender: "Male",
    price: 40000,
    description: "Traditional Seal Point Siamese cat. Very vocal and affectionate.",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop",
    location: "Gujranwala, Punjab",
    city: "Gujranwala",
    province: "Punjab",
    verified: true,
    featured: true,
    sellerName: "Mariam Bibi",
    phone: "+92 300 2223344",
  },
];

async function main() {
  console.log("Seeding database...");

  // Create a demo user
  const demoUser = await prisma.user.upsert({
    where: { email: "demo@animalmandihub.com" },
    update: {},
    create: {
      name: "Demo User",
      email: "demo@animalmandihub.com",
      password: "$2b$10$placeholder", // will be replaced with actual hash
      phone: "+92 300 0000000",
    },
  });

  console.log("Demo user created:", demoUser.id);

  // Create listings
  for (const listing of listings) {
    const created = await prisma.listing.create({
      data: {
        ...listing,
        userId: demoUser.id,
      },
    });
    console.log("Created listing:", created.name);
  }

  console.log(`Seeded ${listings.length} listings.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
